version: '3.8'

services:
  web:
    build: .
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A src worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A src beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
